name: Deploy to Google Cloud

on:
  push:
    branches:
      - main
    paths:
      - 'deploy/**'
      - 'app.yaml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: "devops-team-14-863342"
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy application
        run: gcloud app deploy --quiet
