name: Lint Code with Pylint and MyPy

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Run Pylint and MyPy on a specific file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install pylint mypy

      - name: Run Pylint on brandi_dog.py
        run: |
          pylint server/brandi_dog.py

      - name: Run MyPy on brandi_dog.py
        run: |
          mypy server/brandi_dog.py
